version: 2

jobs:
  build:
    working_directory: /go/src/logger
    docker:
      - image: golang:1.13.4
        environment:
          - ELASTICSEARCH_URL: http://127.0.0.1:9200
          - GO111MODULE: "on"
          - RUN_ONCE: true
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
        environment:
          - discovery.type: single-node
    steps:
      - checkout
      - run:
          name: Wait For Elasticsearch
          command: |
            sleep 15 && wget --waitretry=10 --retry-connrefused -v http://127.0.0.1:9200/
      - run:
          name: Create Directory
          command: |
            mkdir -p .coverage
      - run:
          name: Build
          command: |
            go build -o logger
      - run:
          name: Go Test
          command: |
            go test -vet=off -v -tags test -coverprofile=/tmp/cov.out ./...
      - run:
          name: Go Tool
          command: |
            go tool cover -html=/tmp/cov.out -o=.coverage/cov.html
      - store_artifacts:
          path: .coverage
          destination: coverage
